import time
import os

def clearTerm():
    command = 'clear'       #vai limpar o terminal
    if os.name in ('nt', 'dos'):
        command = 'cls'
    os.system(command)

def runningMap(x):          #executa os métodos do simulador e printa após cada execução única de método.
    x.fillQueues()
    pacientesTotal = x.getAll()
    leitosTotal = x.getOccuped()
    pacientesLi = x.getDischarged()

    leitosAdulto, leitosPed, leitosNeo = x.getBeds()
    pacientesAdulto, pacientesPed, pacientesNeo = x.getPacients()

    pacientesMelhora = x.getDis()
    pacientesMorto = x.getDied()
    print("====================================== \033[1;34mAtualizando estado dos leitos\033[0;0m ========================================")
    print(" ")
    print("\033[1;32mPacientes em Fila:\033[0;0m", pacientesTotal, ", \033[1;32mLeitos Ocupados:\033[0;0m", leitosTotal, ", \033[1;32mPacientes Liberados do Leito:\033[0;0m", pacientesLi)
    print(" ")
    print("\033[2;30m=================================\033[0;0m\033[4;33mLeitos Disponíveis\033[0;0m\033[2;30m===========================\033[0;0m")
    print(" ")
    print("                        Adulto:", leitosAdulto, "| Pediátrico:", leitosPed, "| Neonatal", leitosNeo)
    print(" ")
    print("\033[2;30m==================================\033[0;0m\033[4;33mFila de espera\033[0;0m\033[2;30m==============================\033[0;0m")
    print(" ")
    print("                        Adulto:", pacientesAdulto, "| Pediátrico:", pacientesPed, "| Neonatal", pacientesNeo)
    print("\033[2;30m==============================================================================\033[0;0m")
    print(" ")
    print("\033[1;32mPacientes que melhoraram na fila:\033[0;0m", pacientesMelhora, ", \033[1;32mPacientes que morreram esperando:\033[0;0m", pacientesMorto)
    print(" ")

    time.sleep(2)

    clearTerm()
    x.fillStacks()
    pacientesTotal = x.getAll()
    leitosTotal = x.getOccuped()
    pacientesLi = x.getDischarged()
    leitosAdulto, leitosPed, leitosNeo = x.getBeds()
    pacientesAdulto, pacientesPed, pacientesNeo = x.getPacients()

    pacientesMelhora = x.getDis()
    pacientesMorto = x.getDied()
    print("====================================== \033[1;34mAtualizando estado dos leitos\033[0;0m ========================================")
    print(" ")
    print("\033[1;32mPacientes em Fila:\033[0;0m", pacientesTotal, ", \033[1;32mLeitos Ocupados:\033[0;0m", leitosTotal, ", \033[1;32mPacientes Liberados do Leito:\033[0;0m", pacientesLi)
    print(" ")
    print("\033[2;30m=================================\033[0;0m\033[4;33mLeitos Disponíveis\033[0;0m\033[2;30m===========================\033[0;0m")
    print(" ")
    print("                        Adulto:", leitosAdulto, "| Pediátrico:", leitosPed, "| Neonatal", leitosNeo)
    print(" ")
    print("\033[2;30m==================================\033[0;0m\033[4;33mFila de espera\033[0;0m\033[2;30m==============================\033[0;0m")
    print(" ")
    print("                        Adulto:", pacientesAdulto, "| Pediátrico:", pacientesPed, "| Neonatal", pacientesNeo)
    print("\033[2;30m==============================================================================\033[0;0m")
    print(" ")
    print("\033[1;32mPacientes que melhoraram na fila:\033[0;0m", pacientesMelhora, ", \033[1;32mPacientes que morreram esperando:\033[0;0m", pacientesMorto)
    print(" ")

    time.sleep(3)

    clearTerm()
    x.allocate()

    pacientesTotal = x.getAll()
    leitosTotal = x.getOccuped()
    pacientesLi = x.getDischarged()
    leitosAdulto, leitosPed, leitosNeo = x.getBeds()
    pacientesAdulto, pacientesPed, pacientesNeo = x.getPacients()

    pacientesMelhora = x.getDis()
    pacientesMorto = x.getDied()
    print("====================================== \033[1;34mAtualizando estado dos leitos\033[0;0m ========================================")
    print(" ")
    print("\033[1;32mPacientes em Fila:\033[0;0m", pacientesTotal, ", \033[1;32mLeitos Ocupados:\033[0;0m", leitosTotal, ", \033[1;32mPacientes Liberados do Leito:\033[0;0m", pacientesLi)
    print(" ")
    print("\033[2;30m=================================\033[0;0m\033[4;33mLeitos Disponíveis\033[0;0m\033[2;30m===========================\033[0;0m")
    print(" ")
    print("                        Adulto:", leitosAdulto, "| Pediátrico:", leitosPed, "| Neonatal", leitosNeo)
    print(" ")
    print("\033[2;30m==================================\033[0;0m\033[4;33mFila de espera\033[0;0m\033[2;30m==============================\033[0;0m")
    print(" ")
    print("                        Adulto:", pacientesAdulto, "| Pediátrico:", pacientesPed, "| Neonatal", pacientesNeo)
    print("\033[2;30m==============================================================================\033[0;0m")
    print(" ")
    print("\033[1;32mPacientes que melhoraram na fila:\033[0;0m", pacientesMelhora, ", \033[1;32mPacientes que morreram esperando:\033[0;0m", pacientesMorto)
    print(" ")

    time.sleep(3)

    clearTerm()
    x.attPacinBed()
    pacientesTotal = x.getAll()
    leitosTotal = x.getOccuped()
    pacientesLi = x.getDischarged()
    leitosAdulto, leitosPed, leitosNeo = x.getBeds()
    pacientesAdulto, pacientesPed, pacientesNeo = x.getPacients()

    pacientesMelhora = x.getDis()
    pacientesMorto = x.getDied()
    print("====================================== \033[1;34mAtualizando estado dos leitos\033[0;0m ========================================")
    print(" ")
    print("\033[1;32mPacientes em Fila:\033[0;0m", pacientesTotal, ", \033[1;32mLeitos Ocupados:\033[0;0m", leitosTotal, ", \033[1;32mPacientes Liberados do Leito:\033[0;0m", pacientesLi)
    print(" ")
    print("\033[2;30m=================================\033[0;0m\033[4;33mLeitos Disponíveis\033[0;0m\033[2;30m===========================\033[0;0m")
    print(" ")
    print("                        Adulto:", leitosAdulto, "| Pediátrico:", leitosPed, "| Neonatal", leitosNeo)
    print(" ")
    print("\033[2;30m==================================\033[0;0m\033[4;33mFila de espera\033[0;0m\033[2;30m==============================\033[0;0m")
    print(" ")
    print("                        Adulto:", pacientesAdulto, "| Pediátrico:", pacientesPed, "| Neonatal", pacientesNeo)
    print("\033[2;30m==============================================================================\033[0;0m")
    print(" ")
    print("\033[1;32mPacientes que melhoraram na fila:\033[0;0m", pacientesMelhora, ", \033[1;32mPacientes que morreram esperando:\033[0;0m", pacientesMorto)
    print(" ")

    time.sleep(3)

    clearTerm()

    x.attInQueue()
    pacientesTotal = x.getAll()
    leitosTotal = x.getOccuped()
    pacientesLi = x.getDischarged()
    leitosAdulto, leitosPed, leitosNeo = x.getBeds()
    pacientesAdulto, pacientesPed, pacientesNeo = x.getPacients()

    pacientesMelhora = x.getDis()
    pacientesMorto = x.getDied()
    print("====================================== \033[1;34mAtualizando estado dos leitos\033[0;0m ========================================")
    print(" ")
    print("\033[1;32mPacientes em Fila:\033[0;0m", pacientesTotal, ", \033[1;32mLeitos Ocupados:\033[0;0m", leitosTotal, ", \033[1;32mPacientes Liberados do Leito:\033[0;0m", pacientesLi)
    print(" ")
    print("\033[2;30m=================================\033[0;0m\033[4;33mLeitos Disponíveis\033[0;0m\033[2;30m===========================\033[0;0m")
    print(" ")
    print("                        Adulto:", leitosAdulto, "| Pediátrico:", leitosPed, "| Neonatal", leitosNeo)
    print(" ")
    print("\033[2;30m==================================\033[0;0m\033[4;33mFila de espera\033[0;0m\033[2;30m==============================\033[0;0m")
    print(" ")
    print("                        Adulto:", pacientesAdulto, "| Pediátrico:", pacientesPed, "| Neonatal", pacientesNeo)
    print("\033[2;30m==============================================================================\033[0;0m")
    print(" ")
    print("\033[1;32mPacientes que melhoraram na fila:\033[0;0m", pacientesMelhora, ", \033[1;32mPacientes que morreram esperando:\033[0;0m", pacientesMorto)
    print(" ")

    time.sleep(3)

    clearTerm()